version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/powervc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/powervs"
    schedule:
      interval: "weekly"